
Q0 = "Q0"
TEXT = "text"
QUERY = "query"
QUERY_ID = "query_ID"
QID = "qid"
DOC_NO = "docno"
DOCID = "doc_ID"
LABEL = "label"
RANK = "rank"
TAG = "tag"
SCORE = "score"
FEATURE = "feature"
FLAG = "flag"
input_column_names = [QUERY_ID, DOCID, FEATURE, FLAG]